# Generated by Django 4.1.3 on 2023-10-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee_info", "0004_alter_information_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="elevel",
            field=models.CharField(
                choices=[
                    ("ปวช.", "ปวช."),
                    ("ปวส.", "ปวส."),
                    ("ปริญญาตรี", "ปริญญาตรี"),
                    ("สูงกว่าปริญญาตรี", "สูงกว่าปริญญาตรี"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="gender",
            field=models.CharField(
                choices=[("ชาย", "ชาย"), ("หญิง", "หญิง")], max_length=255
            ),
        ),
    ]
